language: objective-c
osx_image: xcode10.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
- env
- locale
- gem install cocoapods --prerelease --no-document --quiet
- gem install xcpretty --no-document --quiet
- pod --version
- xcpretty --version
- xcodebuild -version
- xcodebuild -showsdks
script:
- set -o pipefail
- .bump-version.sh
- carthage build --no-skip-current --platform macOS SwiftSVG
- carthage archive SwiftSVG
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: FYwiYljcsZGaz5DgNY5R8i9y4MlEhnGlw8GXBixVvlPDIMBZ3a7JGA5R2PQYY3gYLBcK5AgVzhdCN4u1/b2hZJBdlDhrRVdqsKAjJE2diSg3EwrrYZVLj+wuYhJeGTcUF8C7CY3lrRe/7lBq4ezJ5nuThdYUi5o9uZsAFeREjOvMbCMdvYTFw+LP50J70hW06CdEf4UZcE8fFRG7caxa50U9tMEOL6eJCmsTIw+LDubdavdR6q6tNCa4nOYA9kWBol++7aCHYj1abZjqY9d+KgfiNppm1FsXZ1tMzmF2RfzHq5P0Xj46yXLt0UjlyS7l7zQfM18afuwfo4p/RwsyegYY4VQG6iNkFus6qCdrhpwflfrezSKufa5PgpsDSrbffD3j6VldmRG6EWQqaMiX17DoG7DQnFjvHUiBp2D4t7LCBcdwRUyIz6ApQzeKy3dsvOOouJlh+J6auonpTXw7OVPwVS4Z8D7AFCIA1qcn7ztnkJR+cakYMQKWUp52678CPGv/zTM7IhT66JHZEaftyGPwrqIeZlEhhAb835r0TXsWkyFARRaU0fsqikg4qmTmb6USSWQkClKywSc6A3jj/svWgQUQsjAZ3ApAmaPSdfC6I4RAPySuzuRtol6MJjE2gjE/fE1pqUMhNBfCPv774fDnCyCHP8JumGC7Qdkdy+I=
  file: SwiftSVG.framework.zip
  on:
    repo: flinto/SwiftSVG
    tags: true
